#!/bin/bash

sudo mkdir /usr/local/keyshell

sudo mv keyshell.py /usr/local/keyshell/keyshell.py
sudo mv keysdec.py /usr/local/keyshell/keysdec.py

sudo chmod 755 setupkeyboard
sudo mv setupkeyboard /usr/local/bin/setupkeyboard

sudo chmod 755 keyshell
sudo mv keyshell /usr/local/bin/keyshell
