#!/bin/bash

sudo mkdir /usr/local/keyshell

sudo cp keyshell.py /usr/local/keyshell/keyshell.py
sudo cp keysdec.py /usr/local/keyshell/keysdec.py

sudo chmod 755 setupkeyboard
sudo cp setupkeyboard /usr/local/bin/setupkeyboard

sudo chmod 755 keyshell
sudo cp keyshell /usr/local/bin/keyshell
